server {
  listen 80;
  server_name _;
  server_tokens on;
  autoindex on;

  location / {
    add_header Access-Control-Allow-Origin *;
    root /app/dist;
  }

  location ~ /\.(env|git) {
    allow all;
  }
}
